test_technique:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: system
      dbname: sales_Bdd
      threads: 1
