
{{ config(alias='raw_transactions') }}

SELECT
    *  EXCLUDE(SHIPPING_CITY)  ,
    CASE 
        WHEN UPPER(SHIPPING_CITY) LIKE 'LONDON%' THEN 'LONDON' 
        WHEN UPPER(SHIPPING_CITY) LIKE '%VILA NOVA DE FAMALICAO%' THEN 'VILA NOVA DE FAMALICAO' 
        WHEN UPPER(SHIPPING_CITY) LIKE '%SAO DOMINGOS DE RANA%' THEN 'SAO DOMINGOS DE RANA' 
        WHEN UPPER(SHIPPING_CITY) LIKE '%MOITA%' THEN 'MOITA DO RIBATEJO' 
        WHEN UPPER(SHIPPING_CITY) LIKE '%LISBON%' THEN 'LISBON' 
        WHEN UPPER(SHIPPING_CITY) LIKE '%OEIRAS%' or UPPER(SHIPPING_CITY) LIKE 'ALGES%' THEN 'OEIRAS' --Algers c'est un village de la ville oeiras
        ELSE UPPER(SHIPPING_CITY)
    END AS SHIPPING_CITY

FROM 
    {{ source('Sales', 'transactions') }}
